### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by laiyoi** [fishaudio/audio-preprocess#4]
不知道为什么fap没有加进环境变量，所以直接这样开，但是报错了，python版本3.10.7 windows10
PS E:\下载\audio-preprocess-main> E:\python\pyton3.10.7\Scripts\fap.exe --help
Traceback (most recent call last):
  File "E:\python\pyton3.10.7\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\python\pyton3.10.7\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\python\pyton3.10.7\Scripts\fap.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'fish_audio_preprocess'
PS E:\下载\audio-preprocess-main>
PS E:\下载\audio-preprocess-main>
PS E:\下载\audio-preprocess-main> E:\python\pyton3.10.7\Scripts\fap.exe
Traceback (most recent call last):
  File "E:\python\pyton3.10.7\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\python\pyton3.10.7\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\python\pyton3.10.7\Scripts\fap.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'fish_audio_preprocess'

**Comment by leng-yue** [comment]
你是 pip 安装的么, 这也太奇怪了

**Comment by laiyoi** [comment]
是啊

**Comment by laiyoi** [comment]
> 你是 pip 安装的么， 这也太奇怪了

是啊

**Comment by leng-yue** [comment]
只能建议重新安装试试了...

**Comment by yajunjiao** [comment]
解决了吗？
